### ISSUE TITLE
events: Location display, outbound link, show date range or local time

### ISSUE THREAD

**Issue by shayne** [tailscale-dev/tailscale-dev#10]
I apologize if this is on the list but I wanted to file it, just in case.

During or after the Events Markdown refactor (#9) we should consider how to display the link dates, ranges, times, and locations.

For example (sketch):
![image](https://user-images.githubusercontent.com/79330/213873196-d78713df-beb2-4115-92e6-5c8bf56403ef.png)

**Comment by tylersmalley** [comment]
Done
