### ISSUE TITLE
Support for search

### ISSUE THREAD

**Issue by tylersmalley** [tailscale-dev/tailscale-dev#2]
It is essential that we provide a way to effectively search across the content on the site beyond string matching.

Search should support faceting by tags, as well as a full-text search. We plan to have the data persist in the repository, which opens up some non-traditional opportunities for accomplishing this.

I plan to expand on the details further, but I want to get some ideas down while it's in my head. The following uses Elasticsearch, which I am the most familiar with at this time, having previously worked at the company. However, many services/products would allow us to accomplish something similar.

Two options

### Have a centralized Elasticsearch cluster on either [Elastic Cloud](https://cloud.elastic.co/home), [AWS](https://aws.amazon.com/opensearch-service/), or self-hosted.

1. Before a deployment, we would create a new index based on the current Git hash.
2. Index all data into the new index
3. The deployed would point to the Git hash based index
4. Drop old indices

### Deploy Elasticsearch with the application container

During the creation of the application container:

1. Install Elasticsearch
2. Index all data
3. Persisting the data directory in the container

This is not traditional, but it might be more than enough for our use while not requiring us to maintain a centralized cluster. Since the dataset is small and the searches are simple, the overhead should not be a lot (<1GB RAM, 1CPU).

## Events
front matter+:
* location (gis?)
* date (year, year+month)

## Posts
front matter+:
*

**Comment by Xe** [comment]
Replaced with tailscale/corp#11543
