### ISSUE TITLE
Add pronouns 

### ISSUE THREAD

**Issue by tylersmalley** [tailscale-dev/tailscale-dev#40]
We should add pronouns to the author's grey matter markdown

Related to https://github.com/tailscale-dev/tailscale-dev/issues/22

**Comment by Xe** [comment]
If we need a data type for this, I suggest grabbing data from https://pronouns.within.lgbt and even potentially linking to there, eg: [pronouns.within.lgbt/they](https://pronouns.within.lgbt/they). I host pronouns.within.lgbt and I am willing to make any API changes required for integration or slurping up data. The big thing is the core pronoun datatype:
```typescript
export interface Pronoun {
  nominative: string; // subject of sentence
  accusative: string; // object of sentence
  determiner: string; // indirect possessive
  possessive: string; // direct possessive
  reflexive: string; // talking about oneself
  singular: bool; // if surrounding words should be inflected as singular or not
}
```
But realistically sticking in a they/them link to the pronouns education service should be Good Enough:tm:.
