### ISSUE TITLE
Events Off-by-One

### ISSUE THREAD

**Issue by jeremytanner** [tailscale-dev/tailscale-dev#45]
Event dates are showing on the site one day earlier than the date in the event markdown file, looks like date parsing is off-by-one. 

`date: 2023-02-09` turns into `February 8, 2023`

**Comment by tylersmalley** [comment]
I have a [PR](https://github.com/tailscale-dev/tailscale-dev/pull/43) that changes the date parsing, I will check to see if it resolves this issue.

A hack in the meantime is you can set `displayDate` in the markdown grey matter and that string will be displayed instead. We're currently doing that [here](https://github.com/tailscale-dev/tailscale-dev/blob/main/data/events/2023/cloud-native-security-con-na.mdx?plain=1#L4) for an event that spans two days.
