### ISSUE TITLE
Add community content warning

### ISSUE THREAD

**Issue by tylersmalley** [tailscale-dev/tailscale-dev#68]
Posts that are from non-Tailscalar's, or are more personal posts, should be labeled such that they do not express the views of Tailscale the company.

**Comment by tylersmalley** [comment]
@thisisparker could you come up with a blurb we can use for this and I will get it added to the site?

**Comment by tylersmalley** [comment]
This is completed for external contributions. @thisisparker, have a preface we could add for `personal` tagged posts?

**Comment by shayne** [comment]
Decision to make this part of the upcoming preflight checklist for content articles

**Comment by tylersmalley** [comment]
The site will not contain personal posts, and Parker will add something to his preflight checklist.
